export const s = {
  root: { display: 'flex', minHeight: '100vh', backgroundColor: '#F1F5F9', fontFamily: "'Inter', -apple-system, sans-serif" },
  sidebar: { width: '240px', minWidth: '240px', display: 'flex', flexDirection: 'column', padding: '0', position: 'sticky', top: 0, height: '100vh' },
  sidebarBrand: { display: 'flex', alignItems: 'center', gap: '10px', padding: '24px 20px 20px', borderBottom: '1px solid rgba(255,255,255,0.06)' },
  brandIcon: { width: '36px', height: '36px', backgroundColor: '#2563EB', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  brandName: { fontWeight: '700', fontSize: '15px', color: '#F8FAFC', letterSpacing: '-0.3px' },
  nav: { padding: '16px 12px', flex: 1, display: 'flex', flexDirection: 'column', gap: '2px' },
  navItem: { display: 'flex', alignItems: 'center', gap: '10px', padding: '10px 12px', borderRadius: '8px', color: '#94A3B8', fontSize: '13.5px', cursor: 'pointer', transition: 'background 0.15s' },
  navItemActive: { display: 'flex', alignItems: 'center', gap: '10px', padding: '10px 12px', borderRadius: '8px', backgroundColor: '#1E3A5F', color: '#60A5FA', fontSize: '13.5px', fontWeight: '600', cursor: 'pointer' },
  sidebarFooter: { display: 'flex', alignItems: 'center', gap: '10px', padding: '16px 16px', borderTop: '1px solid rgba(255,255,255,0.06)' },
  sidebarAvatar: { width: '34px', height: '34px', minWidth: '34px', backgroundColor: '#2563EB', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '12px', fontWeight: '700', color: '#fff' },
  sidebarName: { fontSize: '13px', fontWeight: '600', color: '#F1F5F9', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  sidebarEmail: { fontSize: '11px', color: '#64748B', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  sidebarLogout: { background: 'none', border: 'none', color: '#64748B', cursor: 'pointer', padding: '4px', display: 'flex', alignItems: 'center' },
  main: { flex: 1, padding: '32px 36px', display: 'flex', flexDirection: 'column', gap: '24px', minWidth: 0 },
  topbar: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  pageTitle: { fontSize: '22px', fontWeight: '700', color: '#0F172A', margin: 0 },
  pageSubtitle: { fontSize: '13px', color: '#94A3B8', margin: '4px 0 0', textTransform: 'capitalize' },
  topbarRight: { display: 'flex', alignItems: 'center', gap: '12px' },
  roleAdmin: { fontSize: '11px', fontWeight: '700', letterSpacing: '0.5px', backgroundColor: '#FEF3C7', color: '#B45309', padding: '4px 10px', borderRadius: '20px' },
  roleUser: { fontSize: '11px', fontWeight: '700', letterSpacing: '0.5px', backgroundColor: '#DBEAFE', color: '#1D4ED8', padding: '4px 10px', borderRadius: '20px' },
  primaryBtn: { display: 'flex', alignItems: 'center', gap: '6px', border: 'none', padding: '10px 18px', borderRadius: '8px', fontSize: '13.5px', fontWeight: '600', cursor: 'pointer', boxShadow: '0 1px 3px rgba(37,99,235,0.3)' },
  metricsRow: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '16px' },
  metricCard: { backgroundColor: '#fff', borderRadius: '12px', overflow: 'hidden', display: 'flex', alignItems: 'center', boxShadow: '0 1px 3px rgba(0,0,0,0.06)', position: 'relative' },
  metricBar: { width: '4px', height: '100%', minHeight: '80px', flexShrink: 0 },
  metricInner: { flex: 1, padding: '18px 16px' },
  metricLabel: { fontSize: '11px', fontWeight: '700', color: '#94A3B8', letterSpacing: '0.5px', textTransform: 'uppercase', marginBottom: '6px' },
  metricValue: { fontSize: '30px', fontWeight: '800', lineHeight: 1 },
  metricIcon: { width: '40px', height: '40px', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center', marginRight: '16px', fontSize: '18px', flexShrink: 0 },
  tableCard: { borderRadius: '12px', overflow: 'hidden' },
  tableHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '20px 24px 16px', borderBottom: '1px solid #F1F5F9', flexWrap: 'wrap', gap: '12px' },
  tableTitle: { fontSize: '16px', fontWeight: '700', color: '#0F172A', margin: 0 },
  filterRow: { display: 'flex', gap: '6px' },
  filterSelect: { padding: '6px 12px', borderRadius: '20px', border: '1px solid #E2E8F0', backgroundColor: '#fff', color: '#374151', fontSize: '12.5px', cursor: 'pointer', outline: 'none' },
  chip: { padding: '6px 14px', borderRadius: '20px', border: '1px solid #E2E8F0', backgroundColor: 'transparent', color: '#64748B', fontSize: '12.5px', cursor: 'pointer', fontWeight: '500' },
  chipActive: { padding: '6px 14px', borderRadius: '20px', border: '1px solid #2563EB', backgroundColor: '#EFF6FF', color: '#2563EB', fontSize: '12.5px', cursor: 'pointer', fontWeight: '600' },
  tableScroll: { overflowX: 'auto' },
  table: { width: '100%', borderCollapse: 'collapse', minWidth: '900px' },
  th: { padding: '10px 16px', textAlign: 'left', fontSize: '11px', fontWeight: '700', color: '#94A3B8', letterSpacing: '0.5px', textTransform: 'uppercase', backgroundColor: '#F8FAFC', borderBottom: '1px solid #E2E8F0', whiteSpace: 'nowrap' },
  tr: { borderBottom: '1px solid #F1F5F9', transition: 'background 0.1s' },
  tdMono: { padding: '14px 16px', fontFamily: 'monospace', fontSize: '12px', color: '#2563EB', fontWeight: '600', whiteSpace: 'nowrap' },
  tdMain: { padding: '14px 16px', minWidth: '200px' },
  tdTitle: { fontSize: '13.5px', fontWeight: '600', color: '#0F172A', marginBottom: '2px' },
  tdSub: { fontSize: '12px', color: '#94A3B8', lineHeight: '1.4' },
  tdText: { padding: '14px 16px', fontSize: '13px', color: '#374151', whiteSpace: 'nowrap' },
  emptyCell: { padding: '48px 16px', textAlign: 'center' },
  emptyState: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '10px', color: '#CBD5E1', fontSize: '14px' },
  authorChip: { display: 'flex', alignItems: 'center', gap: '8px' },
  authorAvatar: { width: '28px', height: '28px', backgroundColor: '#EFF6FF', color: '#2563EB', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '10px', fontWeight: '700', flexShrink: 0 },
  categoryTag: { backgroundColor: '#F1F5F9', color: '#475569', padding: '3px 8px', borderRadius: '4px', fontSize: '11.5px', fontWeight: '500' },
  statusBadge: { display: 'inline-flex', alignItems: 'center', gap: '6px', padding: '4px 10px', borderRadius: '20px', fontSize: '12px', fontWeight: '600' },
  statusDot: { width: '6px', height: '6px', borderRadius: '50%', flexShrink: 0 },
  statusBtn: { backgroundColor: 'transparent', border: '1px solid #E2E8F0', color: '#374151', padding: '5px 10px', borderRadius: '6px', fontSize: '11.5px', fontWeight: '500', cursor: 'pointer', whiteSpace: 'nowrap', transition: 'all 0.15s' },
  configRow: { display: 'flex', flexDirection: 'column', gap: '4px', padding: '12px 0', borderBottom: '1px solid #F1F5F9' },
  configLabel: { fontSize: '11px', fontWeight: '700', color: '#94A3B8', letterSpacing: '0.5px' },
  configValue: { fontSize: '14px', fontWeight: '500', color: '#0F172A' },
  overlay: { position: 'fixed', inset: 0, display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000 },
  modal: { borderRadius: '16px', padding: '32px', width: '100%', maxWidth: '480px' },
  modalHead: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '24px' },
  modalTitle: { fontSize: '18px', fontWeight: '700', color: '#0F172A', margin: '0 0 4px' },
  modalSub: { fontSize: '13px', color: '#94A3B8', margin: 0 },
  closeBtn: { background: 'none', border: 'none', color: '#94A3B8', cursor: 'pointer', padding: '2px', display: 'flex' },
  errorBox: { display: 'flex', alignItems: 'center', gap: '8px', backgroundColor: '#FEF2F2', color: '#DC2626', padding: '10px 14px', borderRadius: '8px', fontSize: '13px', marginBottom: '18px' },
  field: { display: 'flex', flexDirection: 'column', gap: '6px' },
  fieldLabel: { fontSize: '12px', fontWeight: '600', color: '#475569', letterSpacing: '0.3px' },
  fieldInput: { padding: '10px 14px', borderRadius: '8px', border: '1.5px solid #E2E8F0', fontSize: '13.5px', color: '#0F172A', outline: 'none', backgroundColor: '#F8FAFC', width: '100%', boxSizing: 'border-box' },
  cancelBtn: { padding: '10px 20px', borderRadius: '8px', border: '1.5px solid #E2E8F0', backgroundColor: 'transparent', color: '#64748B', fontSize: '13.5px', fontWeight: '600', cursor: 'pointer' },
  submitBtn: { flex: 1, padding: '10px 20px', borderRadius: '8px', border: 'none', backgroundColor: '#2563EB', color: '#fff', fontSize: '13.5px', fontWeight: '600', cursor: 'pointer', boxShadow: '0 1px 3px rgba(37,99,235,0.3)' },
  infoBlock: { display: 'flex', flexDirection: 'column', gap: '3px', padding: '10px 12px', backgroundColor: '#F8FAFC', borderRadius: '8px', border: '1px solid #E2E8F0' },
  infoLabel: { fontSize: '10px', fontWeight: '700', color: '#94A3B8', letterSpacing: '0.5px', textTransform: 'uppercase' },
  infoValue: { fontSize: '13.5px', fontWeight: '500', color: '#0F172A' },
  commentBubble: { padding: '10px 14px', backgroundColor: '#F8FAFC', borderRadius: '10px', border: '1px solid #E2E8F0' },
};
